### ISSUE TITLE
Wrong link to docker hub

### ISSUE THREAD

**Issue by Agares** [wayfair-tremor/tremor-www-docs#9]
Hey, the link to the docker image here: https://www.tremor.rs/getting-started/starting/#get-tremor gives me a 404.
This is the URL that it currently points to: https://hub.docker.com/r/tremor/tremor

**Comment by Licenser** [comment]
hi thanks fort reporting this, the link should point to https://hub.docker.com/r/tremorproject/tremor :) will fix!

**Comment by Licenser** [comment]
fixed once the page rebuilds, thanks again.

**Comment by Agares** [comment]
Would you mind also adding more details on the dockerhub page? Currently the overview is empty, would be great to at least have information about the distro that the image is based on :)

**Comment by Licenser** [comment]
good point, added it as a todo at https://github.com/wayfair-tremor/tremor-runtime/issues/109
